
model: ResNet
loss_weight:
  hm_weight: 1
  wh_weight: 1
  ang_weight: 1
  reg_weight: 0.1
learning_rate: 1.25e-4
num_epochs: 150
data_dir: '/home/nagano/workspace/R-CenterNet/data/airplane360'
output_pth: './best.pth'